baseURL = 'https://moulin-madeuc.fr/'
title = 'Moulin Madeuc'
theme = 'hugo-theme-nostyleplease'
buildFuture = true

defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = false

[params]
  favicon = "favicon.png"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[languages]
  [languages.fr]
    languageName = "Français"
    weight = 1
    contentDir = "content/fr"

  [languages.en]
    languageName = "English"
    weight = 2
    contentDir = "content/en"