baseURL = 'https://moulin-madeuc.fr/'
locale = 'en-us'
title = 'Moulin Madeuc'
theme = 'hugo-theme-nostyleplease'
buildFuture = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true